//! Canonical suite for Assignment 01 — Vault withdrawal limit.
//!
//! ─────────────────────────────────────────────────────────────────────────
//! DO NOT EDIT THIS FILE. It is sealed: the submission checker compares its
//! blob SHA against the upstream copy, and any change fails your submission
//! before the tests are even read.
//!
//! It is also deliberately self-contained. It does not `mod common`, because
//! Checkpoint 6 has you editing `tests/common/mod.rs` — a grader that shared
//! your harness would be grading code you control.
//! ─────────────────────────────────────────────────────────────────────────
//!
//! What it checks, in the language of the assignment:
//!   - `max_withdraw` exists, is a u64, and sits AFTER the two bumps
//!   - it is set from the `initialize` argument, per vault, not hardcoded
//!   - `withdraw` allows amounts below the cap
//!   - `withdraw` allows EXACTLY the cap          (`<=`, not `<`)
//!   - `withdraw` rejects cap + 1 with a declared Anchor error
//!   - the rejection happens BEFORE the transfer, so nothing moves
//!   - deposit is untouched: the cap is a withdrawal limit only

#![allow(dead_code)]

use {
    anchor_lang::{
        prelude::Pubkey,
        solana_program::{instruction::Instruction, system_program},
        InstructionData, ToAccountMetas,
    },
    litesvm::{
        types::{FailedTransactionMetadata, TransactionMetadata},
        LiteSVM,
    },
    solana_keypair::Keypair,
    solana_message::{Message, VersionedMessage},
    solana_signer::Signer,
    solana_transaction::versioned::VersionedTransaction,
};

const VAULT_STATE_SEED: &[u8] = b"vault_state";
const VAULT_SEED: &[u8] = b"vault";
const ONE_SOL: u64 = 1_000_000_000;

/// Byte offsets into the VaultState account.
/// 0..8   Anchor discriminator
/// 8      vault_bump : u8
/// 9      bump       : u8
/// 10..18 max_withdraw : u64 little-endian
const OFF_VAULT_BUMP: usize = 8;
const OFF_STATE_BUMP: usize = 9;
const OFF_MAX_WITHDRAW: usize = 10;

// ── harness ──────────────────────────────────────────────────────────────

fn setup_svm() -> LiteSVM {
    let program_id = lamports_vault::id();
    let mut svm = LiteSVM::new();
    let bytes = include_bytes!("../../../target/deploy/lamports_vault.so");
    svm.add_program(program_id, bytes).unwrap();
    svm
}

fn fund(svm: &mut LiteSVM, pubkey: &Pubkey, lamports: u64) {
    svm.airdrop(pubkey, lamports).unwrap();
}

fn vault_state_pda(user: &Pubkey) -> (Pubkey, u8) {
    Pubkey::find_program_address(&[VAULT_STATE_SEED, user.as_ref()], &lamports_vault::id())
}

fn vault_pda(user: &Pubkey) -> (Pubkey, u8) {
    Pubkey::find_program_address(&[VAULT_SEED, user.as_ref()], &lamports_vault::id())
}

fn initialize_ix(payer: &Pubkey, max_withdrawal: u64) -> Instruction {
    let (vault_state, _) = vault_state_pda(payer);
    let (vault, _) = vault_pda(payer);

    Instruction::new_with_bytes(
        lamports_vault::id(),
        &lamports_vault::instruction::Initialize { max_withdrawal }.data(),
        lamports_vault::accounts::Initialize {
            user: *payer,
            vault_state,
            vault,
            system_program: system_program::ID,
        }
        .to_account_metas(None),
    )
}

fn deposit_ix(user: &Pubkey, amount: u64) -> Instruction {
    let (vault_state, _) = vault_state_pda(user);
    let (vault, _) = vault_pda(user);

    Instruction::new_with_bytes(
        lamports_vault::id(),
        &lamports_vault::instruction::Deposit { amount }.data(),
        lamports_vault::accounts::Deposit {
            user: *user,
            vault,
            vault_state,
            system_program: system_program::ID,
        }
        .to_account_metas(None),
    )
}

fn withdraw_ix(user: &Pubkey, amount: u64) -> Instruction {
    let (vault_state, _) = vault_state_pda(user);
    let (vault, _) = vault_pda(user);

    Instruction::new_with_bytes(
        lamports_vault::id(),
        &lamports_vault::instruction::Withdraw { amount }.data(),
        lamports_vault::accounts::Withdraw {
            user: *user,
            vault,
            vault_state,
            system_program: system_program::ID,
        }
        .to_account_metas(None),
    )
}

fn send(
    svm: &mut LiteSVM,
    payer: &Keypair,
    instructions: &[Instruction],
) -> Result<TransactionMetadata, FailedTransactionMetadata> {
    let blockhash = svm.latest_blockhash();
    let msg = Message::new_with_blockhash(instructions, Some(&payer.pubkey()), &blockhash);
    let tx = VersionedTransaction::try_new(VersionedMessage::Legacy(msg), &[payer]).unwrap();
    svm.send_transaction(tx)
}

/// A vault with `cap` as its ceiling and `cap + 2 SOL` deposited, so that a
/// withdrawal of exactly `cap` is never limited by the balance.
fn vault_with_cap(cap: u64) -> (LiteSVM, Keypair) {
    let mut svm = setup_svm();
    let user = Keypair::new();
    fund(&mut svm, &user.pubkey(), cap + 20 * ONE_SOL);

    send(&mut svm, &user, &[initialize_ix(&user.pubkey(), cap)])
        .expect("initialize with a max_withdraw argument should succeed");
    send(
        &mut svm,
        &user,
        &[deposit_ix(&user.pubkey(), cap + 2 * ONE_SOL)],
    )
    .expect("deposit should succeed");

    (svm, user)
}

/// Anchor surfaces `require!` failures as a custom program error. Declared
/// errors start at 6000, which is how we tell "your check rejected this" from
/// "the runtime rejected this" (insufficient funds, bad seeds, and so on).
///
/// Read off the Debug form of the error rather than a specific enum so this
/// keeps working across solana crate versions.
fn declared_anchor_error(e: &FailedTransactionMetadata) -> Option<u32> {
    let text = format!("{:?}", e.err);
    let start = text.find("Custom(")? + "Custom(".len();
    let rest = &text[start..];
    let end = rest.find(')')?;
    let code: u32 = rest[..end].trim().parse().ok()?;
    if code >= 6000 {
        Some(code)
    } else {
        None
    }
}

fn read_max_withdraw(svm: &LiteSVM, user: &Pubkey) -> u64 {
    let (vault_state, _) = vault_state_pda(user);
    let account = svm
        .get_account(&vault_state)
        .expect("vault_state account should exist after initialize");
    let data = &account.data;
    assert!(
        data.len() >= OFF_MAX_WITHDRAW + 8,
        "VaultState is {} bytes, too small to hold max_withdraw at offset {}. \
         Did you add `max_withdraw: u64` to the struct?",
        data.len(),
        OFF_MAX_WITHDRAW
    );
    u64::from_le_bytes(
        data[OFF_MAX_WITHDRAW..OFF_MAX_WITHDRAW + 8]
            .try_into()
            .unwrap(),
    )
}

// ── checkpoint 2: the field, in the right place ──────────────────────────

#[test]
fn max_withdraw_is_stored_after_the_two_bumps() {
    let cap = 2 * ONE_SOL;
    let mut svm = setup_svm();
    let user = Keypair::new();
    fund(&mut svm, &user.pubkey(), 30 * ONE_SOL);

    let (vault_state, expected_state_bump) = vault_state_pda(&user.pubkey());
    let (_, expected_vault_bump) = vault_pda(&user.pubkey());

    send(&mut svm, &user, &[initialize_ix(&user.pubkey(), cap)])
        .expect("initialize should succeed");

    let data = svm.get_account(&vault_state).unwrap().data;

    assert_eq!(
        data[OFF_VAULT_BUMP], expected_vault_bump,
        "vault_bump must stay at byte 8 — append max_withdraw, do not prepend it"
    );
    assert_eq!(
        data[OFF_STATE_BUMP], expected_state_bump,
        "bump must stay at byte 9 — append max_withdraw, do not prepend it"
    );
    assert_eq!(
        u64::from_le_bytes(data[OFF_MAX_WITHDRAW..OFF_MAX_WITHDRAW + 8].try_into().unwrap()),
        cap,
        "max_withdraw must be stored at byte 10 as a little-endian u64"
    );
}

// ── checkpoint 3: set from the instruction argument, per vault ───────────

#[test]
fn max_withdraw_comes_from_the_instruction_argument() {
    let cap = 7 * ONE_SOL + 12_345;
    let (svm, user) = vault_with_cap(cap);
    assert_eq!(
        read_max_withdraw(&svm, &user.pubkey()),
        cap,
        "the stored cap must be whatever initialize was called with, not a constant"
    );
}

#[test]
fn the_cap_is_per_vault_not_global() {
    let mut svm = setup_svm();
    let alice = Keypair::new();
    let bob = Keypair::new();
    fund(&mut svm, &alice.pubkey(), 30 * ONE_SOL);
    fund(&mut svm, &bob.pubkey(), 30 * ONE_SOL);

    let alice_cap = ONE_SOL;
    let bob_cap = 5 * ONE_SOL;

    send(&mut svm, &alice, &[initialize_ix(&alice.pubkey(), alice_cap)])
        .expect("alice initialize should succeed");
    send(&mut svm, &bob, &[initialize_ix(&bob.pubkey(), bob_cap)])
        .expect("bob initialize should succeed");

    assert_eq!(read_max_withdraw(&svm, &alice.pubkey()), alice_cap);
    assert_eq!(read_max_withdraw(&svm, &bob.pubkey()), bob_cap);

    send(&mut svm, &alice, &[deposit_ix(&alice.pubkey(), 10 * ONE_SOL)])
        .expect("alice deposit should succeed");
    send(&mut svm, &bob, &[deposit_ix(&bob.pubkey(), 10 * ONE_SOL)])
        .expect("bob deposit should succeed");

    // 2 SOL is over Alice's cap and under Bob's. One vault must reject it and
    // the other must allow it, which no global constant can do.
    let alice_res = send(&mut svm, &alice, &[withdraw_ix(&alice.pubkey(), 2 * ONE_SOL)]);
    assert!(
        alice_res.is_err(),
        "2 SOL is over Alice's 1 SOL cap and must be rejected"
    );

    send(&mut svm, &bob, &[withdraw_ix(&bob.pubkey(), 2 * ONE_SOL)])
        .expect("2 SOL is under Bob's 5 SOL cap and must be allowed");
}

// ── checkpoints 5 + 7: the boundary ──────────────────────────────────────

#[test]
fn withdraw_below_the_cap_succeeds() {
    let cap = 2 * ONE_SOL;
    let (mut svm, user) = vault_with_cap(cap);

    send(&mut svm, &user, &[withdraw_ix(&user.pubkey(), cap - 1)])
        .expect("a withdrawal of one lamport under the cap must succeed");
}

/// The test that separates `<=` from `<`. An implementation using `amount <
/// max_withdraw` passes every other test in this file and fails this one.
#[test]
fn withdraw_of_exactly_the_cap_succeeds() {
    let cap = 2 * ONE_SOL;
    let (mut svm, user) = vault_with_cap(cap);

    let (vault, _) = vault_pda(&user.pubkey());
    let before = svm.get_balance(&vault).unwrap_or_default();

    send(&mut svm, &user, &[withdraw_ix(&user.pubkey(), cap)]).expect(
        "a withdrawal of exactly max_withdraw must succeed — the rule is \
         `amount <= max_withdraw`, not `amount < max_withdraw`",
    );

    let after = svm.get_balance(&vault).unwrap_or_default();
    assert_eq!(
        before - after,
        cap,
        "the vault should have paid out exactly the cap"
    );
}

#[test]
fn withdraw_of_one_over_the_cap_is_rejected() {
    let cap = 2 * ONE_SOL;
    let (mut svm, user) = vault_with_cap(cap);

    let err = send(&mut svm, &user, &[withdraw_ix(&user.pubkey(), cap + 1)])
        .expect_err("a withdrawal of max_withdraw + 1 must be rejected");

    let code = declared_anchor_error(&err).unwrap_or_else(|| {
        panic!(
            "the rejection must come from your own `require!`, which Anchor \
             reports as a custom error numbered 6000 or above. Got: {:?}",
            err.err
        )
    });
    assert!(
        code >= 6000,
        "expected a declared Anchor error, got custom code {code}"
    );
}

/// The cap has to be checked before the CPI, not after. If the transfer runs
/// first the transaction still fails and reverts, so a passing/failing
/// assertion cannot tell the difference — but the logs can: a check that ran
/// first never reaches the "Withdrawing lamports" work.
#[test]
fn an_over_cap_withdrawal_moves_no_lamports() {
    let cap = 2 * ONE_SOL;
    let (mut svm, user) = vault_with_cap(cap);

    let (vault, _) = vault_pda(&user.pubkey());
    let before = svm.get_balance(&vault).unwrap_or_default();

    let _ = send(&mut svm, &user, &[withdraw_ix(&user.pubkey(), cap + 1)]);

    let after = svm.get_balance(&vault).unwrap_or_default();
    assert_eq!(
        before, after,
        "a rejected withdrawal must leave the vault balance untouched"
    );
}

#[test]
fn a_wildly_over_cap_withdrawal_is_rejected_by_the_cap() {
    let cap = ONE_SOL;
    let (mut svm, user) = vault_with_cap(cap);

    let err = send(&mut svm, &user, &[withdraw_ix(&user.pubkey(), 1_000 * ONE_SOL)])
        .expect_err("a withdrawal far over the cap must be rejected");

    assert!(
        declared_anchor_error(&err).is_some(),
        "the cap must be checked before the transfer, so this should fail with \
         your error rather than an insufficient-funds error. Got: {:?}",
        err.err
    );
}

// ── the rest of the program must still work ──────────────────────────────

#[test]
fn deposit_is_not_capped() {
    let cap = ONE_SOL;
    let mut svm = setup_svm();
    let user = Keypair::new();
    fund(&mut svm, &user.pubkey(), 30 * ONE_SOL);

    send(&mut svm, &user, &[initialize_ix(&user.pubkey(), cap)])
        .expect("initialize should succeed");

    send(&mut svm, &user, &[deposit_ix(&user.pubkey(), 10 * ONE_SOL)])
        .expect("max_withdraw limits withdrawals only — deposits above it must still work");
}

#[test]
fn withdraw_without_initialize_still_fails() {
    let mut svm = setup_svm();
    let user = Keypair::new();
    fund(&mut svm, &user.pubkey(), 10 * ONE_SOL);

    let res = send(&mut svm, &user, &[withdraw_ix(&user.pubkey(), ONE_SOL)]);
    assert!(
        res.is_err(),
        "withdraw without a vault_state must still fail"
    );
}

#[test]
fn another_users_vault_cannot_be_drained() {
    let cap = 5 * ONE_SOL;
    let (mut svm, owner) = vault_with_cap(cap);

    let attacker = Keypair::new();
    fund(&mut svm, &attacker.pubkey(), 10 * ONE_SOL);

    let res = send(&mut svm, &attacker, &[withdraw_ix(&attacker.pubkey(), ONE_SOL)]);
    assert!(
        res.is_err(),
        "an attacker with no vault of their own must not be able to withdraw"
    );

    let (owner_vault, _) = vault_pda(&owner.pubkey());
    assert!(
        svm.get_balance(&owner_vault).unwrap_or_default() > 0,
        "the owner's vault must be untouched"
    );
}
